EtchedPixels/Fuzix-Compiler-Kit

test/6809.c
test/6809.h
test/Makefile
test/emu6502.c
test/emu6809.c
test/lib65c816/src/Makefile
test/run-testz80.sh
test/testcrt0_6502.s

I couldn't do a make in test/, and make clean doesn't clean up properly. These changes fix these problems. I also took the liberty of getting emu6502 to exit with a write to a memory location, instead of after a fixed number of clock cycles.

Fix make; make clean up in test/ directory

---

backend-6809.c
test/6809.c
test/emu6809.c

emu6809: get the emulator to FAIL when the exit value is not zero.
backend-6809.c: add code to `gen_helpclean()` to adjust the stack after a call to a helper function.

emu6809: get the emulator to FAIL when the exit value is not zero.

---

backend-6809.c

Along with the node rewrites in the previous pull request, this allows the 6809 backend to compile 0001-unsigned.c which then runs correctly.

backend-6809.c: prepend '_' to several uses of printf(..., namestr())

---

backend.c
support6809/makebool.s
test/testcrt0_6809.s

This fixes tests/0002-signed.c. We also need a word-sized @zero :-)

support6809: __bool and __not were the wrong way around.

---

backend-6800.c

The `cmp` or `sub` operations invalidate the B or D registers. We need to get the backend to re-load them, e.g.
```
i=1;
while (i <= 10) {
printint(i);
i= i + 1;
}
```
Without the change, the code prints 1 1 1 1 1 1 1 1 1 1. With the change, the code prints 1 2 3 4 5 6 7 8 9 10.

backend-6800: cmp_direct() needs to invalidate registers

---

support6809/crt0.s
support6809/dp.s

Given the library uses these, they need to be initialised in the normal crt0.s.

support6809: add @zero and @one to the normal crt0.s

---

support6809/divide32x32.s

This fixes the "missing symbol" errors on more of the tests.

support6809/divide32x32.s: make tmp2 and tmp3 global

---

backend-6800.c

I've replaced the instruction with `puls x` to pull X off the stack.

pop_x(): wrong 6809 instruction

---

backend-6800.c

I borrowed from the z80 backend. This now works:
```
void cprintf(char *fmt, ...);
int x;
int y;
int main() {
for (x=0, y=1; x < 6; x++, y=y+2) {
cprintf("%d %d\n", x, y);
}
return(0);
}
```

backend-6800.c: Bring in the T_COMMA code from another backend.

---

backend-6800.c

Replaced with `tfr a,b` and `tfr b,a`.

backend-6800.c: replace tab and tba instructions for 6809.

---

backend-6800.c

This fixes the `sign` initialisation bug in `_vfnprintf()` and now `printf()` works.

backend-6800.c: fix bug in uniop8_on_s(), wrong stack offset

---

cc.c

This allows me (and others!) to run `gdb` on individual phases, e.g.
```
$ fcc -m6809 -S -O -V -X readdir.c
>readdir.%
[/opt/fcc//lib/cpp -I /opt/fcc//lib/6809/include -D __6809__ -E readdir.c ]
<readdir.%
>readdir.@
[/opt/fcc//lib/cc0 .symtmp299a ]
<readdir.@
>readdir.#
[/opt/fcc//lib/cc1.6800 ]
<readdir.#
>readdir.^
[/opt/fcc//lib/cc2.6800 .symtmp299a 6809 1 ]
<readdir.^
>readdir.s
[/opt/fcc//lib/copt /opt/fcc//lib/rules.6809 ]
```
Now I can do:
```
$ gdb cc2.6800
(gdb) run .symtmp299a 6809 1 <readdir.#
```

cc.c: Add a -V flag to print out the phases. Also, keep the symbol table file when -X is specified.

---

backend-6800.c

This was calculating 16-bit additions incorrectly.

backend-6800.c: op16_on_spi() changed to do add/adc instead of add/add.

---

cc.c

`fcc` didn't like to compile `cc.c` without these changes.

cc.c: fix code with duplicate local variable names.

---

support6303/__cast2f.c
support6303/__castf.c
support65c816/__cast2f.c
support65c816/__castf.c
support6800/__cast2f.c
support6800/__castf.c
support6803/__cast2f.c
support6803/__castf.c
support6809/__cast2f.c
support6809/__castf.c
support68hc11/__cast2f.c
support68hc11/__castf.c
supportnova/__cast2f.c
supportnova/__castf.c
supportnova3/__cast2f.c
supportnova3/__castf.c
supportsuper8/__cast2f.c
supportsuper8/__castf.c
supportz8/__cast2f.c
supportz8/__castf.c
supportz80/__cast2f.c
supportz80/__castf.c

The software floating-point library contains multiple primitives with double underscore prefixes, like
long __castf_l(uint32_t a1);
This compiles to three underscores in the object file, when the compiler only expects two, leading to "unknown symbol" errors when casting floats.

__castf.c: fixed typo in function names

---

supportz80/__negatel.s

This code previously checked for 16-bit carry by testing whether 'inc hl' left the high byte zero:
ld	a,h
or	a
...but this behaves incorrectly in cases like 0x00C0, where the high byte is zero because it started that way, not because it overflowed. The fix is to test whether both bytes are zero:
ld	a,h
or	l

__negatel.s: fixed carry bug when negating longs (Z80)

---

support6800/__castc.s
support6800/__castc_l.s
support6800/__xdiveqc.s

For testing, I used a modified version of 0008-promotion.c
```
int func(signed char a)
{
return a;
}
int lfunc(signed char a)
{
return a;
}
int main(int argc, char *argv[])
{
signed char a;
signed int b;
signed long c;
a = 0xA5;
b = a;
if ((unsigned)b != 0xFFA5)
return 1;
b = 0x1234;
a = b;
if (a != 0x34)
return 2;
a = 0xAB;
if ((unsigned)func(a) != 0xFFAB)
return 3;
a = 0x20;
if ((unsigned)func(a) != 0x0020)
return 4;
a = 0xA5;
c = a;
if ((unsigned long)c != 0xFFFFFFA5)
return 11;
b = 0x1234;
a = b;
if (a != 0x34)
return 12;
a = 0xAB;
if ((unsigned long)lfunc(a) != 0xFFFFFFAB)
return 13;
a = 0x20;
if ((unsigned long)lfunc(a) != 0x00000020)
return 14;
return 0;
}
```

a bit smaller and faster.

---

backend-8070.c

The following code returns 0x34.
```
int main() {
int a = 0x1234;
return a & 0x8000;
}
```
This PR fixes it.

8070: Fix "&" operator

---

support8070/__minusl.s
support8070/__plusl.s

All other sources use __hireg.

8070: Rename __high to __hireg

---

backend-8070.c

This PR fixes:
`@__tmp` to `:__tmp` of all
`ld ea,p%u` to `ld ea,0,p%u` of "-=" operator

8070: Fix addressing errors
